### PR TITLE
Better validators scan

### PR DESCRIPTION
**Pull request by GioviQ**
Fix https://github.com/Blazored/FluentValidation/issues/37

### CODE REVIEW

**Comment by chrissainty** [comment]
Hi @GioviQ, could you explain a bit about what this is fixing, what problem you're having?

I can't accept this as I have no idea from either the issue you opened or what is done in the PR as to what it solves.

**Comment by GioviQ** [comment]
Look at https://github.com/enkodellc/blazorboilerplate/blob/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Admin/Pages/Admin/Translations.razor

             <EditForm Model="@newLocalizationRecord" OnValidSubmit="@SaveNewLocalizationRecord">
                <FluentValidationValidator />
                <ValidationSummary />
                <fieldset>
                    <div class="form-group">
                        <MatSelectItem @bind-Value="@newLocalizationRecord.LocalizationCulture" Items="@LocalizationCultures" Label=@L["Culture"]></MatSelectItem>
                        <MatTextField @bind-Value="@newLocalizationRecord.Text" Label=@L["Translation"] FullWidth="true" TextArea="true"></MatTextField>
                        <MatButton Type="submit" Raised="true">@L["Add"]</MatButton>
                    </div>
                </fieldset>
            </EditForm>

The validator https://github.com/enkodellc/blazorboilerplate/blob/development/src/Shared/BlazorBoilerplate.Shared/Dto/Db/Validators/LocalizationRecordValidator.cs 

is not found scanning the assembly. So validation does not happen.

So I asked @JeremySkynner with https://github.com/FluentValidation/FluentValidation/issues/1522 that told me:

AbstractValidator works fine with interfaces.

So the missing registration of 

     public class LocalizationRecordValidator : LocalizedAbstractValidator<ILocalizationRecord>

is a issue of your repository that I fixed.

You see the issue online here https://blazor-server.quarella.net/admin/translations

Here https://blazor-server.quarella.net/ the admin password.

**Comment by chrissainty** [comment]
Thanks for the context @GioviQ, this all makes sense now. I think my only concern is the caching of the assembly scan results as this could cause problem when .NET5 is released. As lazy loading is an option then, if we cache the results and a new assembly is loaded which contained new Validators, this code would never find them. What are your thoughts?

**Comment by GioviQ** [comment]
Do you think my last commit is enough for lazy loading @chrissainty ?

**Comment by chrissainty** [comment]
Yes, I think that should cover any lazy loaded assemblies. Thank you.

**Review by chrissainty — APPROVED** [review]
Thanks for the contribution @GioviQ

**Comment by GioviQ** [comment]
Sorry but https://github.com/Blazored/FluentValidation/packages/312611 is not published automatically on https://www.nuget.org/packages/Blazored.FluentValidation/.

**Comment by chrissainty** [comment]
Thanks fir spotting that @GioviQ, I've just published it so it will be on NuGet shortly.

**Pull request merged**
